### PR TITLE
Tweak notebooks

### PR DESCRIPTION
**Pull request by ahuang11**
Closes https://github.com/ProjectPythia/web-map-feature-services-cookbook/issues/6

### CODE REVIEW

**Comment by ktyle** [comment]
This looks great; only thing that is failing is the Zenodo DOI tag.

**Comment by ahuang11** [comment]
Not sure how to fix that.

**Comment by brian-rose** [comment]
> This looks great; only thing that is failing is the Zenodo DOI tag.

When we're ready to "publish" this cookbook on the gallery, we will also "release" a tagged version of the source repo on GitHub. That will trigger the archiving on Zenodo and issuing of a DOI. Once that happens, the link failure will go away.

I think we're probably ready to do all those things now that @ktyle has reviewed the content. Let me take a quick look.

**Comment by ahuang11** [comment]
Any updates on this?

**Comment by brian-rose** [comment]
@ahuang11 I see there's a PR open https://github.com/ProjectPythia/cookbook-gallery/pull/144 to publish this on the gallery!

Aside from minting the DOI release, the only issue I see is the thumbnail image on the gallery page:
https://cookbooks.projectpythia.org/_preview/144/

Right now it's a generic Project Pythia logo. Do you want to replace that with something more specific? The gallery thumbnail is specified in _gallery_info.yml

**Comment by ahuang11** [comment]
Okay updated!

**Review by brian-rose — APPROVED** [review]
Great! Let's merge this PR and then we're ready to publish on the gallery.

**Pull request merged**
