### PR TITLE
Update repo to latest template

### PR DESCRIPTION
**Pull request by brian-rose**
This PR does a few things:
- update the environment file to prefer installing packages from conda-forge
- update many links to reflect the new home of the repo
- Some refactoring and personalizing of the repo consistent with the latest cookbook template

### CODE REVIEW

**Comment by brian-rose** [comment]
@ahuang11 please take a look at this!

The link-checker failure for is expected. This will be resolved after the first "release" of the repo on Zenodo, which should coincide with getting it listed on the Pythia gallery.

There's another link failure that needs addressing:
a 404 error for https://charming-ornate-flying-snake.anacondaapps.cloud/

A few other things that need your attention:
- your ORCID and optionally any other metadata (like institutional affiliation) that you want to include in the CITATION.cff file
- some tags for the Pythia gallery. These go in `_gallery_tags.yml`. This will affect how the cookbook is displayed in the [gallery](https://cookbooks.projectpythia.org) once we get it listed there.

You can drop comments here, or feel free to push directly to my PR branch.

**Comment by ahuang11** [comment]
Thanks @brian-rose for wrapping this up!

I suppose I unpublished the app on Anaconda notebook to make room for other apps (oops). For a longer lived solution, I exported it to pyodide / pyscript and hosted it on GitHub pages here: https://ahuang11.github.io/nasa-earth-data-gibs-wms-explorer/

I think(?) this is my ORCID: 0000-0003-2618-084X from https://orcid.org/0000-0003-2618-084X; the affiliation can be Anaconda, Inc.

Suggested tags that I thought of:
Geospatial data
Basemaps
Satellite imagery
Spatial analysis
Data visualization
Geoviews
NASA EarthData GIBS
GIS
hvPlot
(others feel free to add)

Thanks again!

**Comment by brian-rose** [comment]
@ahuang11 one last thing: a short description of the cookbook to go in the `abstract` field of the citation file.

We display this text on the card in the [Cookbook Gallery](https://cookbooks.projectpythia.org)

**Comment by ahuang11** [comment]
Maybe something like
`Learn how to use web map and feature services to easily and quickly provide spatial context, without the need to download and process GBs of data!`

**Comment by brian-rose** [comment]
@ahuang11 if you're happy with all this, please sign off and we'll get this merged and then move toward getting the cookbook listed on the gallery!

**Review by ahuang11 — APPROVED** [review]

**Comment by ahuang11** [comment]
Thanks it looks good to me!

**Pull request merged**
